/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_iMage_geometrify_ParallelTrianglePictureFilter */

#ifndef _Included_org_iMage_geometrify_ParallelTrianglePictureFilter
#define _Included_org_iMage_geometrify_ParallelTrianglePictureFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_iMage_geometrify_ParallelTrianglePictureFilter
 * Method:    calculate
 * Signature: (II[IIIIJ)[I
 */
JNIEXPORT jintArray JNICALL Java_org_iMage_geometrify_ParallelTrianglePictureFilter_calculate
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
